name: Build and Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Build
      run: |
        npm install
        npm test
        npm run build

    - name: Create universal package
      run: |
        npm install -g @vscode/vsce
        vsce package

    - name: Download sys4lang
      uses: robinraju/release-downloader@v1
      with:
        repository: "kichikuou/sys4lang"
        tag: "v0.2.0"
        fileName: "sys4lang-*-windows-x64.zip"
        extract: true

    - name: Create windows package
      run: |
        vsce package --target win32-x64

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: vscode-system4
        path: '*.vsix'

    - name: Publish to marketplace
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        for vsix in *.vsix; do
          vsce publish --packagePath "$vsix"
        done
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
